 CREATE TABLE "ARQ_HEX"."GENCATSENCA"
   (CODCAT NUMBER(10) GENERATED ALWAYS AS IDENTITY INCREMENT BY 10 START WITH 10 MAXVALUE 99999999 MINVALUE 10 CACHE 20 NOT NULL ,
	"CATDESC" VARCHAR2(20 char),
	"CODUSR" VARCHAR2(20 char),
	"FECHCREA" TIMESTAMP (6),
	"FECHMOD" TIMESTAMP (6),
	 CONSTRAINT "GENCATSENCA_PK" PRIMARY KEY ("CODCAT")
  USING INDEX TABLESPACE "ARQ_HEXI"  ENABLE
   );

ALTER TABLE "ARQ_HEX"."GENCATSENCA" MODIFY
(
  CODCAT GENERATED ALWAYS AS IDENTITY INCREMENT BY 10 START WITH 10 MINVALUE 10 MAXVALUE 9999999999 CACHE 20
);


  CREATE TABLE "ARQ_HEX"."GENCATSDETA"
   (	"CODCAT" NUMBER NOT NULL ENABLE,
	"CODCOR" NUMBER NOT NULL ENABLE,
	"CORDESC" VARCHAR2(20 char),
	"CODUSR" VARCHAR2(20 char),
	"FECHCREA" TIMESTAMP (6),
	"FECHMOD" TIMESTAMP (6),
	 CONSTRAINT "GENCATSDETA_PK" PRIMARY KEY ("CODCAT", "CODCOR")
  USING INDEX TABLESPACE "ARQ_HEXI"  ENABLE,
	 CONSTRAINT "GENCATSDETA_GENCATSENCA_FK1" FOREIGN KEY ("CODCAT")
	  REFERENCES "ARQ_HEX"."GENCATSENCA" ("CODCAT") ENABLE
   )
  TABLESPACE "ARQ_HEXD" ;