-- Migración para cambiar TIMESTAMP a TIMESTAMP WITH TIME ZONE
-- Esto corrige el error ORA-18716 al mapear java.time.Instant

-- Modificar columnas en GENCATSENCA
ALTER TABLE "ARQ_HEX"."GENCATSENCA" MODIFY "FECHCREA" TIMESTAMP(6) WITH TIME ZONE;
ALTER TABLE "ARQ_HEX"."GENCATSENCA" MODIFY "FECHMOD" TIMESTAMP(6) WITH TIME ZONE;

-- Modificar columnas en GENCATSDETA
ALTER TABLE "ARQ_HEX"."GENCATSDETA" MODIFY "FECHCREA" TIMESTAMP(6) WITH TIME ZONE;
ALTER TABLE "ARQ_HEX"."GENCATSDETA" MODIFY "FECHMOD" TIMESTAMP(6) WITH TIME ZONE;
